# Generated by Django 3.1.2 on 2020-10-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_quickcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='is_inbound',
            field=models.BooleanField(default=False, verbose_name='inbound'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='is_outbound',
            field=models.BooleanField(default=False, verbose_name='outbound'),
        ),
    ]
